---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: democratic-csi-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CSI_USERNAME: "{{ .dcsi_username }}"
        CSI_PRIVATEKEY: "{{ .dcsi_privatekey }}"
  dataFrom:
    - extract:
        key: democratic-csi
      rewrite:
        - regexp:
            source: "(.*)"
            target: "dcsi_$1"
