---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "${APP}-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "${APP}"
        group: internal
        url: "https://${GATUS_SUBDOMAIN:-${APP}}.jahanson.tech${GATUS_PATH:-/}"
        interval: 1m
        client:
          dns-resolver: tcp://10.1.1.1:53
        conditions:
          - "[STATUS] == ${GATUS_STATUS:-200}"
        alerts:
          - type: pushover
