---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nvidia-device-plugin
spec:
  interval: 30m
  chart:
    spec:
      chart: nvidia-device-plugin
      version: 0.14.1
      sourceRef:
        kind: HelmRepository
        name: nvdp
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    config:
      name: nvidia-plugin-configs
    gfd:
      enabled: true
    nfd:
      enabled: false
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 512Mi
