apiVersion: v1
kind: Pod
metadata:
  name: alpine-debug
  namespace: kube-system
spec:
  #  nodeName: nenya
  containers:
    - name: alpine-debug
      image: alpine
      securityContext:
        privileged: true
      command: ["/bin/ash", "-c", "while true; do sleep 10; done"]
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 4000m
          memory: 4000Mi
