---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./cilium/ks.yaml
  - ./descheduler/ks.yaml
  - ./fstrim/ks.yaml
  - ./metrics-server/ks.yaml
  # - ./multus/ks.yaml
  - ./intel-device-plugin/ks.yaml
  - ./nvidia-device-plugin/ks.yaml
  - ./node-feature-discovery/ks.yaml
  - ./reloader/ks.yaml
  - ./spegel/ks.yaml
