---
# yaml-language-server: $schema=https://ks.hsn.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: maintainerr
spec:
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/jorenn92/maintainerr
              tag: 2.0.0@sha256:7377075b39985b64369d1fddd1ea9ad39f59a8e98c777e2da4cd7041a93b6380
            env:
              TZ: America/Chicago
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 1Gi

    service:
      main:
        ports:
          http:
            port: 6246

    ingress:
      main:
        enabled: true
        className: internal-nginx
        hosts:
          - host: &host "{{ .Release.Name }}.jahanson.tech"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: maintainerr
        globalMounts:
          - path: /opt/data
