---
# yaml-language-server: $schema=https://ks.hsn.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: maintainerr
spec:
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: ghcr.io/jorenn92/maintainerr
              tag: 2.0.2@sha256:4e0f5199f09b8a1fc7d9933c1ecbf508b6d4f18b6f8d1e40bd0453dc14c80a5c
            env:
              TZ: America/Chicago
            resources:
              requests:
                cpu: 5m
                memory: 128Mi
              limits:
                memory: 1Gi
            pod:
              securityContext:
                runAsUser: ${APP_UID}
                runAsGroup: ${APP_GID}
                fsGroup: ${APP_GID}
                fsGroupChangePolicy: "OnRootMismatch"

    service:
      main:
        ports:
          http:
            port: 6246

    ingress:
      main:
        enabled: true
        className: internal-nginx
        hosts:
          - host: &host "{{ .Release.Name }}.jahanson.tech"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: maintainerr
        globalMounts:
          - path: /opt/data
