---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stablediffusion-checkpoints
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: openebs-hostpath
