---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubevirt
  namespace: flux-system
spec:
  interval: 30m
  url: https://git.hsn.dev/jahanson/kubevirt-flux.git
  ref:
    branch: v1.2.2
  ignore: |
    # exclude all
    /*
    # include files
    !/deploy
