---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    # Homelab
    age: >-
      age1eqlaq205y5jre9hu5hvulywa7w3d4qyxwmafneamxcn7nejesedsf4q9g6
  - path_regex: .*\.sops\.(env|ini|json|toml)
    # Homelab
    age: >-
      age1eqlaq205y5jre9hu5hvulywa7w3d4qyxwmafneamxcn7nejesedsf4q9g6
  - path_regex: (ansible|terraform|talos)/.*\.sops\.ya?ml
    # Homelab
    age: >-
      age1eqlaq205y5jre9hu5hvulywa7w3d4qyxwmafneamxcn7nejesedsf4q9g6
