---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./ingress.yaml
  - ./podmonitor.yaml
patchesStrategicMerge:
  - cluster.yaml
replacements:
  - source:
      kind: ConfigMap
      name: emqx-conf
      fieldPath: data.emqx.conf
    targets:
      - select:
          kind: EMQX
          name: emqx
        fieldPaths:
          - spec.config.data
        options:
          delimiter: |
generatorOptions:
  disableNameSuffixHash: true
