---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: autobrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: autobrr-secret
    template:
      engineVersion: v2
      data:
        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_DATABASE: autobrr
        AUTOBRR__POSTGRES_HOST: "postgres-primary-real.database.svc"
        AUTOBRR__POSTGRES_USER: "{{ .AUTOBRR_POSTGRES_USER }}"
        AUTOBRR__POSTGRES_PASS: "{{ .AUTOBRR_POSTGRES_PASSWORD }}"
        AUTOBRR__POSTGRES_PORT: "5432"
        AUTOBRR__SESSION_SECRET: "{{ .AUTOBRR_SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: autobrr
