apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.hsn.dev
  labels:
    app: cert-manager-webhook-dnsimple
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/webhook-dnsimple-webhook-tls"
spec:
  group: acme.hsn.dev
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: Local
    namespace: cert-manager
  version: v1alpha1