---
version: v1
flags:
  migStrategy: "mixed"
  plugin:
    deviceListStrategy: "envvar"
    deviceIDStrategy: "uuid"
sharing:
  timeSlicing:
    resources:
      - name: nvidia.com/gpu
        replicas: 3
