on:
  push:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:37.363.8@sha256:d5d20fda77bffb65bb4099389d6cb064e1e06b085bc547e10330bf82317c9693
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          show-progress: false

      - name: Renovate
        uses: ./.forgejo/actions/renovate
        with:
          endpoint: https://git.hsn.dev/api/v1/
          token: ${{ secrets.RENOVATE_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
          args: ${{ github.repository }} --platform gitea # --autodiscover
          save-cache: true
