---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: grafana
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-grafana
  data:
    - match:
        secretKey: dbname
        remoteRef:
          remoteKey: grafana
          property: GF_DATABASE_NAME
    - match:
        secretKey: host
        remoteRef:
          remoteKey: grafana
          property: GF_DATABASE_HOST
    - match:
        secretKey: user
        remoteRef:
          remoteKey: grafana
          property: GF_DATABASE_USER
    - match:
        secretKey: password
        remoteRef:
          remoteKey: grafana
          property: GF_DATABASE_PASSWORD
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gatus
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-gatus
  data:
    - match:
        secretKey: uri
        remoteRef:
          remoteKey: gatus
          property: DATABASE_URI
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: prowlarr
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-prowlarr
  data:
    - match:
        secretKey: host
        remoteRef:
          remoteKey: prowlarr
          property: PROWLARR__POSTGRES_HOST
    - match:
        secretKey: user
        remoteRef:
          remoteKey: prowlarr
          property: PROWLARR__POSTGRES_USER
    - match:
        secretKey: password
        remoteRef:
          remoteKey: prowlarr
          property: PROWLARR__POSTGRES_PASSWORD
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: sonarr
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-sonarr
  data:
    - match:
        secretKey: host
        remoteRef:
          remoteKey: sonarr
          property: SONARR__POSTGRES_HOST
    - match:
        secretKey: user
        remoteRef:
          remoteKey: sonarr
          property: SONARR__POSTGRES_USER
    - match:
        secretKey: password
        remoteRef:
          remoteKey: sonarr
          property: SONARR__POSTGRES_PASSWORD
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: radarr
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-radarr
  data:
    - match:
        secretKey: host
        remoteRef:
          remoteKey: radarr
          property: RADARR__POSTGRES_HOST
    - match:
        secretKey: user
        remoteRef:
          remoteKey: radarr
          property: RADARR__POSTGRES_USER
    - match:
        secretKey: password
        remoteRef:
          remoteKey: radarr
          property: RADARR__POSTGRES_PASSWORD