---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: grafana
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-grafana
  data:
    - match:
        secretKey: dbname
        remoteRef:
          remoteKey: grafana
          property: GF_DATABASE_NAME
    - match:
        secretKey: host
        remoteRef:
          remoteKey: grafana
          property: GF_DATABASE_HOST
    - match:
        secretKey: user
        remoteRef:
          remoteKey: grafana
          property: GF_DATABASE_USER
    - match:
        secretKey: password
        remoteRef:
          remoteKey: grafana
          property: GF_DATABASE_PASSWORD
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gatus
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-gatus
  data:
    - match:
        secretKey: dbname
        remoteRef:
          remoteKey: gatus
          property: pg_database
    - match:
        secretKey: port
        remoteRef:
          remoteKey: gatus
          property: pg_port
    - match:
        secretKey: user
        remoteRef:
          remoteKey: gatus
          property: pg_username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: gatus
          property: pg_password
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: prowlarr
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-prowlarr
  data:
    - match:
        secretKey: host
        remoteRef:
          remoteKey: prowlarr
          property: PROWLARR_POSTGRES_HOST
    - match:
        secretKey: user
        remoteRef:
          remoteKey: prowlarr
          property: PROWLARR_POSTGRES_USER
    - match:
        secretKey: password
        remoteRef:
          remoteKey: prowlarr
          property: PROWLARR_POSTGRES_PASSWORD
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: sonarr
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-sonarr
  data:
    - match:
        secretKey: host
        remoteRef:
          remoteKey: sonarr
          property: SONARR_POSTGRES_HOST
    - match:
        secretKey: user
        remoteRef:
          remoteKey: sonarr
          property: SONARR_POSTGRES_USER
    - match:
        secretKey: password
        remoteRef:
          remoteKey: sonarr
          property: SONARR_POSTGRES_PASSWORD
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: radarr
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-radarr
  data:
    - match:
        secretKey: host
        remoteRef:
          remoteKey: radarr
          property: RADARR_POSTGRES_HOST
    - match:
        secretKey: user
        remoteRef:
          remoteKey: radarr
          property: RADARR_POSTGRES_USER
    - match:
        secretKey: password
        remoteRef:
          remoteKey: radarr
          property: RADARR_POSTGRES_PASSWORD
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: atuin
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-atuin
  data:
    - match:
        secretKey: host
        remoteRef:
          remoteKey: atuin
          property: ATUIN_POSTGRES_HOST
    - match:
        secretKey: user
        remoteRef:
          remoteKey: atuin
          property: ATUIN_POSTGRES_USER
    - match:
        secretKey: password
        remoteRef:
          remoteKey: atuin
          property: ATUIN_POSTGRES_PASSWORD
---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: jellyseerr
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-pguser-jellyseerr
  data:
    - match:
        secretKey: host
        remoteRef:
          remoteKey: jellyseerr
          property: JELLYSEERR_POSTGRES_HOST
    - match:
        secretKey: user
        remoteRef:
          remoteKey: jellyseerr
          property: JELLYSEERR_POSTGRES_USER
    - match:
        secretKey: password
        remoteRef:
          remoteKey: jellyseerr
          property: ATUIN_POSTGRES_PASSWORD
