---
apiVersion: v1
kind: Service
metadata:
  labels:
    postgres-operator.crunchydata.com/cluster: postgres
    postgres-operator.crunchydata.com/role: primary
  name: postgres-primary-real
  namespace: media
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: postgres
  selector:
    postgres-operator.crunchydata.com/cluster: postgres
    postgres-operator.crunchydata.com/role: master
  type: ClusterIP
