---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: thanos-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_HOST: s3.hsn.dev
        S3_BUCKET: "{{ .minio_thanos_bucket_name }}"
        S3_ACCESS_KEY: "{{ .minio_thanos_access_key }}"
        S3_SECRET_KEY: "{{ .minio_thanos_secret_key }}"
        S3_REGION: us-east-1
  dataFrom:
    - extract:
        key: Minio
      rewrite:
        - regexp:
            source: "(.*)"
            target: "minio_$1"
