---
# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_release_version: "v1.29.0+k3s1"
k3s_install_hard_links: true
k3s_become: true
k3s_etcd_datastore: true
k3s_registration_address: 10.5.0.2
# /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_urls:
  # Essential Prometheus Operator CRDs (the rest are installed with the kube-prometheus-stack helm release)
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
    filename: custom-prometheus-podmonitors.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_prometheusrules.yaml
    filename: custom-prometheus-prometheusrules.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_scrapeconfigs.yaml
    filename: custom-prometheus-scrapeconfigs.yaml
  - url: https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/v0.70.0/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
    filename: custom-prometheus-servicemonitors.yaml
# /var/lib/rancher/k3s/server/manifests
k3s_server_manifests_templates:
  - custom-coredns-helmchart.yaml.j2
  - custom-cilium-helmchart.yaml.j2
# k3s_registries:
#   mirrors:
#     docker.io:
#       endpoint: ["http://harbor.hsn.dev/v2/docker.io"]
#     ghcr.io:
#       endpoint: ["http://harbor.hsn.dev/v2/ghcr.io"]