---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: flood
  namespace: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: flood-secret
  data:
    - secretKey: FLOOD_OPTION_QBUSER
      remoteRef:
        key: flood
        property: username
    - secretKey: FLOOD_OPTION_QBPASS
      remoteRef:
        key: flood
        property: password
