---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app flood
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: qbittorrent
      namespace: qbittorrent
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      flood:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: jesec/flood
              tag: master@sha256:449f93644402b60929cb87e61aedd2494781c07012467e5c7ac35e70d983323b
            env:
              FLOOD_OPTION_RUNDIR: /data
              FLOOD_OPTION_AUTH: none
              FLOOD_OPTION_QBURL: http://qbittorrent.qbittorrent.svc.cluster.local
            resources:
              requests:
                memory: 250Mi
                cpu: 15m
              limits:
                memory: 512Mi
    service:
      app:
        controller: *app
        ports:
          http:
            port: 80
    ingress:
      app:
        enabled: true
        className: "internal-nginx"
        hosts:
          - host: &host "flood.jahanson.tech"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: *app
        globalMounts:
          - path: /data
