---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kubevirt-cdi
  namespace: flux-system
spec:
  targetNamespace: cdi
  dependsOn:
    - name: kubevirt
    - name: openebs-cluster
  path: ./deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubevirt-cdi
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  patches:
    - patch: |
        $patch: delete
        apiVersion: v1
        kind: Namespace
        metadata:
          name: cdi
      target:
        kind: Namespace
        name: cdi
    - patch: |
        apiVersion: cdi.kubevirt.io/v1beta1
        kind: CDI
        metadata:
          name: not-used
        spec:
          cloneStrategyOverride: snapshot
          config:
            featureGates:
            - HonorWaitForFirstConsumer
          customizeComponents: {}
          imagePullPolicy: IfNotPresent
          infra:
            nodeSelector:
              kubernetes.io/os: linux
            tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
          workload:
            nodeSelector:
              kubernetes.io/os: linux
      target:
        group: cdi.kubevirt.io
        kind: CDI
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app kubevirt-cdi-addl
  namespace: flux-system
spec:
  targetNamespace: cdi
  dependsOn:
    - name: kubevirt-cdi
  interval: 10m
  path: "./kubernetes/apps/cdi/cdi/app/"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
