---
# yaml-language-server: $schema=https://ks.hsn.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dragonflydb-metrics
  namespace: database
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
      app: dragonfly
  podTargetLabels:
    - app
  namespaceSelector:
    matchNames:
      - database
  podMetricsEndpoints:
    - port: admin
