---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: coder-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CODER__POSTGRES_HOST: "postgres-primary-real.database.svc"
        CODER__POSTGRES_PORT: "5432"
        CODER__POSTGRES_USER: "{{ .CODER_POSTGRES_USER }}"
        CODER__POSTGRES_PASSWORD: "{{ .CODER_POSTGRES_PASSWORD }}"
        CODER__POSTGRES_MAIN_DB: coder
        CODER_PG_CONNECTION_URL: "postgres://{{ .CODER_POSTGRES_USER }}:{{ .CODER_POSTGRES_PASSWORD }}@postgres-primary-real.database.svc/coder"

  dataFrom:
    - extract:
        key: coder
