---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: emqx-conf
    files:
      - emqx.conf=./resources/emqx.conf
replacements:
  - source:
      kind: ConfigMap
      name: emqx-conf
    targets:
      - fieldPaths:
          - spec.config.data
        options:
          create: true
        select:
          kind: EMQX
          name: emqx
generatorOptions:
  disableNameSuffixHash: true
