---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ./cloudflare/externalsecret.yaml
  - ./cloudflare/issuer-letsencrypt-prod.yaml
  - ./cloudflare/issuer-letsencrypt-staging.yaml
  - ./dnsimple/externalsecret.yaml
  - ./dnsimple/issuer-zerossl-prod.yaml
