---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: 1.0.120
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      interval: 30m
  values:
    reloader:
      reloadStrategy: annotations
