---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-secret
    template:
      engineVersion: v2
      data:
        CUSTOM_PUSHOVER_TOKEN: "{{ .gatus_token }}"
        CUSTOM_PUSHOVER_USER_KEY: "{{ .userkey_jahanson }}"
        DATABASE_URI: "postgresql://{{ .pg_username }}:{{ .pg_password }}@postgres-primary-real.database.svc:{{ .pg_port }}/{{ .pg_database }}"
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: gatus
