---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nicehash
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nicehash-secret
    template:
      type: Opaque
      data:
        MINING_ADDRESS: "{{ .MINING_ADDRESS }}"
  dataFrom:
    - extract:
        key: nicehash
