---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent
  namespace: flux-system
spec:
  targetNamespace: qbittorrent
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: "./kubernetes/apps/qbittorrent/qbittorrent/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: true
  dependsOn:
    - name: openebs
    - name: volsync
    - name: external-secrets-stores
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 2Gi
      VOLSYNC_STORAGECLASS: openebs-zfs
      VOLSYNC_SNAPSHOTCLASS: openebs-zfs
---
# yaml-language-server: $schema=https://ks.hsn.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app qbittorrent-tools
  namespace: flux-system
spec:
  targetNamespace: qbittorrent
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/qbittorrent/qbittorrent/tools
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
