---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname alertmanager
  namespace: flux-system
spec:
  targetNamespace: observability
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./kubernetes/apps/observability/alertmanager/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: theshire
  wait: true
  dependsOn:
    - name: external-secrets-stores
    - name: rook-ceph-cluster
