---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: loki-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        S3_BUCKET_HOST: s3.hsn.dev
        S3_BUCKET_NAME: "{{ .minio_thanos_bucket_name }}"
        S3_ACCESS_KEY: "{{ .minio_loki_access_key }}"
        S3_SECRET_KEY: "{{ .minio_loki_secret_key }}"
        S3_BUCKET_REGION: us-east-1
  dataFrom:
    - extract:
        key: minio
      rewrite:
        - regexp:
            source: "(.*)"
            target: "minio_$1"
