# yaml-language-server: $schema=https://ks.hsn.dev/operator.victoriametrics.com/vmsingle_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vm-single
  namespace: victoria-metrics
spec:
  retentionPeriod: "1y"
  storage:
    storageClassName: openebs-zfs
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
