---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unpackerr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
       unpackerr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/unpackerr/unpackerr
              tag: 0.13.1@sha256:04fcb43fa70e6db88331962760607842cdf19889e6d35d9d2fde0cf6a1550eaf
            env:
              TZ: America/Chicago
              UN_WEBSERVER_METRICS: "true"
              UN_SONARR_0_URL: http://sonarr.default.svc.cluster.local
              UN_SONARR_0_PATHS_0: /data/nas-media/qb/downloads/complete/sonarr/
              UN_RADARR_0_URL: http://radarr.default.svc.cluster.local
              UN_RADARR_0_PATHS_0: /data/nas-media/qb/downloads/complete/radarr/
            envFrom:
              - secretRef:
                  name: unpackerr-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 4Gi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: unpackerr
        ports:
          http:
            port: 5656
    serviceMonitor:
      app:
        serviceName: unpackerr
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    persistence:
      media:
        type: nfs
        server: 10.1.1.11
        path: /volume1/Media
        advancedMounts:
          unpackerr:
            app:
              - path: /data/nas-media
