---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nginx-ingress-secrets
  namespace: network
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nginx-external-maxmind-secret
    template:
      engineVersion: v2
      data:
        MAXMIND_LICENSE_KEY: "{{ .homelab_nginx }}"
  dataFrom:
    - extract:
        key: Maxmind
