---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    template:
      engineVersion: v2
      data:
        RADARR__API_KEY: "{{ .api_key }}"
        PUSHOVER_TOKEN: "{{ .radarr_token }}"
        PUSHOVER_USER_KEY: "{{ .userkey_jahanson }}"
        RADARR__POSTGRES_HOST: "{{ .RADARR__POSTGRES_HOST }}"
        RADARR__POSTGRES_USER: "{{ .RADARR__POSTGRES_USER }}"
        RADARR__POSTGRES_PASSWORD: "{{ .RADARR__POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: radarr
