---
# yaml-language-server: $schema=https://ks.hsn.dev/cdi.kubevirt.io/storageprofile_v1beta1.json
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    cdi.kubevirt.io: ""
  name: zfs-generic-nfs-csi
spec:
  claimPropertySets:
    - accessModes:
        - ReadWriteMany
        - ReadWriteOnce
      volumeMode: Filesystem
status:
  cloneStrategy: snapshot
  dataImportCronSourceFormat: pvc
  provisioner: org.democratic-csi.nfs
  snapshotClass: zfs-generic-nfs-csi
  storageClass: zfs-generic-nfs-csi
