---
# yaml-language-server: $schema=https://ks.hsn.dev/cdi.kubevirt.io/storageprofile_v1beta1.json
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
    cdi.kubevirt.io: ""
  name: openebs-zfs
spec:
  claimPropertySets:
    - accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
  snapshotClass: openebs-zfs
status:
  claimPropertySets:
    - accessModes:
        - ReadWriteOnce
      volumeMode: Block
  cloneStrategy: clone
  dataImportCronSourceFormat: pvc
  provisioner: openebs.io/local
  snapshotClass: openebs-zfs
  storageClass: openebs-zfs
