---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cross-seed-secret
    template:
      engineVersion: v2
      data:
        config.js: |
          module.exports = {
            action: "inject",
            apiKey: "{{.CROSS_SEED_API_KEY}}",
            dataCategory: "cross-seed",
            delay: 30,
            duplicateCategories: true,
            includeEpisodes: true,
            includeNonVideos: true,
            includeSingleEpisodes: true,
            linkDir: "/data/nas-media/qb/downloads/complete/cross-seed",
            linkType: "hardlink",
            matchMode: "safe",
            outputDir: "/config",
            port: 80,
            qbittorrentUrl: "http://qbittorrent.qbittorrent.svc.cluster.local",
            skipRecheck: true,
            torrentDir: "/qbittorrent/qBittorrent/BT_backup",
            torznab: []
          };
  dataFrom:
    - extract:
        key: cross-seed
