---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-secret
    template:
      engineVersion: v2
      data:
        SONARR__API_KEY: "{{ .api_key }}"
        PUSHOVER_TOKEN: "{{ .sonarr_token }}"
        PUSHOVER_USER_KEY: "{{ .userkey_jahanson }}"
        SONARR__POSTGRES__HOST: "postgres-primary-real.database.svc"
        SONARR__POSTGRES__USER: "{{ .SONARR_POSTGRES_USER }}"
        SONARR__POSTGRES__PASSWORD: "{{ .SONARR_POSTGRES_PASSWORD }}"
        SONARR__POSTGRES__PORT: "5432"
        SONARR__POSTGRES__MAINDB: &dbName sonarr_main
        SONARR__AUTH__APIKEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: sonarr
