---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich-microservices
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      immich-microservices:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.100.0
            command: /bin/sh
            args:
              - ./start-microservices.sh
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 4000Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            envFrom:
              - configMapRef:
                  name: immich-app-config
            env:
              DB_URL:
                valueFrom:
                  secretKeyRef:
                    name: immich-pguser-immich
                    key: uri
    pod:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      runtimeClassName: nvidia
    service:
      app:
        controller: immich-microservices
        enabled: false
    persistence:
      media:
        enabled: true
        type: nfs
        server: 10.1.1.13
        path: /eru/media/immich
        globalMounts:
          - path: /usr/src/app/upload