---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellyseerr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: jellyseerr-secret
    template:
      engineVersion: v2
      data:
        DB_TYPE: "postgres" # Which DB engine to use. The default is "sqlite". To use postgres, this needs to be set to "postgres"
        DB_HOST: "postgres-primary-real.database.svc"
        DB_PORT: "5432"
        DB_USER: "{{ .JELLYSEERR_POSTGRES_USER }}"
        DB_PASS: "{{ .JELLYSEERR_POSTGRES_PASSWORD }}"
        DB_NAME: "jellyseerr"
        DB_LOG_QUERIES: 'false' # Whether to log the DB queries for debugging
        DB_USE_SSL: 'false' # Whether to enable ssl for database connection
  dataFrom:
    - extract:
        key: pushover
    - extract:
        key: jellyseerr
