---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app zfs-scrub
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  values:
    controllers:
      kubanetics:
        type: cronjob
        cronjob:
          schedule: "@weekly"
          parallelism: 1 # Set to my total number of nodes
        containers:
          app:
            image:
              repository: ghcr.io/aarnaud/talos-debug-tools
              tag: latest-6.6.29
            command: ["/bin/bash", "-c"]
            args:
              - |
                # Trim filesystems
                chroot /host /usr/local/sbin/zpool scrub nahar
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 128Mi
            securityContext:
              privileged: true
        pod:
          hostNetwork: true
          hostPID: true
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app
    persistence:
      netfs:
        type: hostPath
        hostPath: /sys
        hostPathType: Directory
        globalMounts:
          - path: /sys
            readOnly: true
      dev:
        type: hostPath
        hostPath: /dev
        hostPathType: Directory
        globalMounts:
          - path: /dev
      modules:
        type: hostPath
        hostPath: /lib/modules
        hostPathType: ""
        globalMounts:
          - path: /lib/modules
      udev:
        type: hostPath
        hostPath: /run/udev
        hostPathType: ""
        globalMounts:
          - path: /run/udev
      localtime:
        type: hostPath
        hostPath: /etc/localtime
        hostPathType: ""
        globalMounts:
          - path: /etc/localtime
      host:
        type: hostPath
        hostPath: /
        hostPathType: Directory
        globalMounts:
          - path: /host
      efivars:
        type: hostPath
        hostPath: /sys/firmware/efi/efivars
        hostPathType: ""
        globalMounts:
          - path: /sys/firmware/efi/efivars
