---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: zfs-scrub-configmap
    files:
      - zfs-scrub.sh=./resources/zfs-scrub.sh
