---
# yaml-language-server: $schema=https://ks.hsn.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vm-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: victoria-metrics-operator
      version: 0.35.2
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: vm-operator
    rbac:
      pspEnabled: false
    operator:
      enable_converter_ownership: true
      useCustomConfigReloader: true
    resources:
      limits:
        cpu: 220m
        memory: 320Mi
      requests:
        cpu: 80m
        memory: 120Mi
