---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ./allow-ssh.yaml
  - ./apiserver.yaml
  - ./cilium-health.yaml
  - ./cilium-vxlan.yaml
  - ./core-dns.yaml
  - ./etcd.yaml
  - ./hubble-relay.yaml
  - ./hubble-ui.yaml
  - ./kubelet.yaml

