---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HASS_ELEVATION: "{{ .hass_elevation }}"
        HASS_LATITUDE: "{{ .hass_latitude }}"
        HASS_LONGITUDE: "{{ .hass_longitude }}"
  dataFrom:
    - extract:
        key: home-assistant
      rewrite:
        - regexp:
            source: "(.*)"
            target: "hass_$1"