---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/instance: system
    app.kubernetes.io/name: namespace
    app.kubernetes.io/part-of: dragonfly-operator
    control-plane: controller-manager
  name: dragonfly-operator-system
