---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: security
spec:
  provider:
    onepassword:
      connectHost: http://10.5.0.5:8080
      vaults:
        hsn.dev: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: security
