apiVersion: v1
kind: Secret
metadata:
    name: onepassword-connect-token
    namespace: security
stringData:
    token: ENC[AES256_GCM,data:FeJIuyd82zKIa4DBaDzV59Ed/2HE9V62UaooPwycZu4hpUb+5gH1cHyPvwvCNGmGlWzaKK2njV9utYEEF5mIG7Ugo9b04nqOOYySm/SmvH7y2FwoS3VWvIXkhNUn6Wpjh2vDxNw6HV4TQ++Pht8MxXZiPIpiuhIEM0H6qF0gI4Ll7Xj8Rh9k6UthJd6E7qUkp8K0SeIKOyVYsJwi6CwH7zjhbvx6q+2N4/hTfIp8nmD5sz+0Kk7CuZ88/mqKG9tjkZHipmIGi2r66elqs6gHRLHk2j8zORbmyQ93YOyhmgUcHJCknBkDgYD901JGsfNgeCMLAW91wF3e2JgKIsAwkXiMnjLsupLoIQeyf+tU+wJINX/M3nfdvcPwRIJwf+9S6/8VSuxpYNrxGAMrrjGGxsEMNivj4Pfj7J5spM/BCsFZhiTgYdtcS8PZPpkDoiJIkHgcDHQn3Ik33YklPFMgjq1Vpo32Z9jPIhsCodIAWEXUqxyVWqxJkRQhIvOZO0D8C+bagjAi464oWRiXBl9SfRgbm8j0J3eHiVJsNwj03zvRxRYMphalNPtIY95karPipfwrjmjD8hfq0iOfq5k/n8W00aQdff3Fup9mx2fZ2g+5k1v5D67r6udKveQD1F6rhElBAmpW1B48o4ZGtUY3pHHCzKuxzRp7mjZzYCgv8FTehwYbqg6rnYurfoLhaK4E1wSS7umvK0tRL8yfZwl9Xx/K4eVI1pKXXnM9ijjG1sQa257Ur5H4H3IniXH4CGeW7ywOtuBc1SysK0Xn5zmGOtQsCC1nonZDpYDrJg4vx1GyTRe3Nzba/WRtbeA6QPo3c2vExUBpP9G8DnnMYIMtKbGJ,iv:Fsl5ajL3B1doXDpilMXUsjtaLY9cHIo60FJTz295KGE=,tag:i51kPeObQPE4iGxe5aePQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1eqlaq205y5jre9hu5hvulywa7w3d4qyxwmafneamxcn7nejesedsf4q9g6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZHo5aWdxVndCUkdCSEc4
            dkFkeGQ5ZkY2Rk4wM0RuaGxvU2g3K1JGTEJNCnJpYm1DbXBQOTdGSjVITU8xaE5D
            RGRoYjVHWVh5Rno4THIvMmlZWWJVWncKLS0tIEVQNmQ1TTA2V0VjdWw2SU9WbUNt
            VkJYWGZnMEJOdlkweS82RjFQdGtHekkK1LCJ2Ww1Ar1fXcepNTldf/hiBVbYdGRf
            NwCgEa18sMHVVx1XdhBT67bhQewIr6yYHk4jX8y22ScS9GTx9syD4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-04T15:22:45Z"
    mac: ENC[AES256_GCM,data:jJdPqNrszVidWGFACwxPlis2cc3qPRNxAcjONQfV/fHdk+HlzgI3LnKqSS3clRzhBicvlsXEo0hqqNf70CsGV3tcbZIoxyCHHu+RsbqON8HxRQoDeSGnio7JnP6YbnRkqxlPOrMG8yFUz+a7fuqad6nw6dnIuiKxbOoL7ZdgqCg=,iv:uWgmmfQy54xVh3t/lIYr7K9O9M8X0dDtT0p9MP3wseQ=,tag:rPtQmSGscJ3Fxc3/32Pw1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
