---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vector-aggregator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vector-aggregator-secret
    template:
      engineVersion: v2
      data:
        GEOIPUPDATE_ACCOUNT_ID: "{{ .account_id }}"
        GEOIPUPDATE_LICENSE_KEY: "{{ .vector_license_key }}"
  dataFrom:
    - extract:
        key: maxmind