---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: alertmanager-silencer
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  dependsOn:
    - name: kube-prometheus-stack
      namespace: observability
  values:
    controllers:
      alertmanager-silencer:
        type: cronjob
        cronjob:
          schedule: "@daily"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/kubanetics
              tag: 2024.4.1@sha256:28addcaf03a83863d58e45ed98fc5339a24fec65900907beee38fe7fe8117bfe
            env:
              SCRIPT_NAME: alertmanager-silencer.sh
              ALERTMANAGER_URL: http://alertmanager-operated.observability.svc.cluster.local:9093
              MATCHERS_0: alertname=NodeCPUHighUsage job=node-exporter
              MATCHERS_1: alertname=CephNodeDiskspaceWarning device=/dev/xvda6
              MATCHERS_2: alertname=CephNodeDiskspaceWarning device=/dev/nvme0n1p6
              MATCHERS_3: alertname=CephNodeDiskspaceWarning device=/dev/sda6
              MATCHERS_4: alertname=CephNodeDiskspaceWarning device=/dev/vda6
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 25m
              limits:
                memory: 128Mi
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
