---
# yaml-language-server: $schema=https://ks.hsn.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: zfs-exporter
spec:
  staticConfigs:
    - targets:
        - 10.1.1.13:9134
  metricsPath: /metrics
