---
# yaml-language-server: $schema=https://ks.hsn.dev/operator.victoriametrics.com/vmalert_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: cluster
spec:
  evaluationInterval: 1m
  useStrictSecurity: true
  selectAllByDefault: true
  datasource:
    url: http://vmsingle-cluster.observability.svc:8429
  notifiers:
    - url: http://alertmanager.observability.svc:9093
  remoteRead:
    url: http://vmsingle-cluster.observability.svc:8429
  remoteWrite:
    url: http://vmsingle-cluster.observability.svc:8429
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    fsGroup: 65534
  resources:
    requests:
      cpu: 3m
    limits:
      memory: 128Mi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/instance: cluster
          app.kubernetes.io/name: vmalert
