---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zerossl-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zerossl-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        api-token: "{{ .dnsimple_cert_manager_api_token }}"
        eab-hmac-key: "{{ .zerossl_eab_hmac_key }}"
  dataFrom:
    - extract:
        key: DNSimple
      rewrite:
        - regexp:
            source: "(.*)"
            target: "dnsimple_$1"
    - extract:
        key: ZeroSSL
      rewrite:
        - regexp:
            source: "(.*)"
            target: "zerossl_$1"
