---
# yaml-language-server: $schema=https://ks.hsn.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer-zerossl-prod
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    email: "joe@veri.dev"
    privateKeySecretRef:
      name: zerossl-production
    externalAccountBinding:
      keyID: feJODDijN9gypthMXaHtVA
      keySecretRef:
        name: zerossl-secret
        key: eab-hmac-key
      keyAlgorithm: HS256
    solvers:
      - dns01:
          webhook:
            groupName: acme.hsn.dev
            solverName: dnsimple
            config:
              apiKeySecretRef:
                name: zerossl-secret
                key: api-token
        selector:
          dnsZones:
            - jahanson.tech
