---
# yaml-language-server: $schema=https://ks.hsn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linkwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: linkwarden-secret
    template:
      engineVersion: v2
      data:
        NEXTAUTH_SECRET: "{{ .LINKWARDEN_NEXTAUTH_SECRET }}"
        LINKWARDEN_POSTGRES_REAL_HOST: "postgres-primary-real.database.svc"
        DATABASE_URL: |-
          postgres://{{ .LINKWARDEN_POSTGRES_USER }}:{{ .LINKWARDEN_POSTGRES_PASSWORD }}@{{ .LINKWARDEN_POSTGRES_REAL_HOST }}/linkwarden
  dataFrom:
    - extract:
        key: linkwarden
