---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fj-runner-01-disk1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
  storageClassName: openebs-zfs
