---
# yaml-language-server: $schema=https://ks.hsn.dev/kubevirt.io/virtualmachine_v1.json
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fj-runner-01
  namespace: default
  uid: e0725361-eb07-44bc-bb01-7a1dba39622a
  labels:
  kubevirt-manager.io/managed: "true"
  kubevirt.io/domain: fj-runner-01
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt-manager.io/managed: "true"
        kubevirt.io/domain: fj-runner-01
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 2
        devices:
          disks:
            - disk: {}
              name: disk1
              bootOrder: 0
            - disk: {}
              name: disk2
              bootOrder: 1
          interfaces:
            - bridge: {}
              name: net1
          networkInterfaceMultiqueue: true
        machine:
          type: q35
        resources:
          requests:
            memory: 8Gi
      networks:
        - name: net1
          pod: {}
      nodeSelector:
        kubernetes.io/hostname: shadowfax
      priorityClassName: vm-standard
      volumes:
        - dataVolume:
            name: default-fj-runner-01-disk1
          name: disk1
        - dataVolume:
            name: default-fj-runner-01-disk2
          name: disk2
