---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fj-runner-02-disk1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 160Gi
  storageClassName: local-hostpath-nvme1
