---
# yaml-language-server: $schema=https://ks.hsn.dev/kubevirt.io/virtualmachine_v1.json
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fj-runner-02
  namespace: default
spec:
  running: false
  template:
    spec:
      architecture: amd64
      domain:
        clock:
          timezone: "America/Chicago"
        cpu:
          cores: 4
          sockets: 1
          threads: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: disk1
            - cdrom:
                bus: sata
              name: nixosiso
          interfaces:
            - bridge: {}
              name: net1
          networkInterfaceMultiqueue: true
        firmware:
          # this sets the bootloader type
          bootloader:
            efi:
              secureBoot: false
        machine:
          type: q35
        resources:
          requests:
            memory: 8Gi
      networks:
        - name: net1
          pod: {}
      nodeSelector:
        kubernetes.io/hostname: shadowfax
      priorityClassName: vm-standard
      volumes:
        - dataVolume:
            name: fj-runner-02-disk1
          name: disk1
        - dataVolume:
            name: "nixos-minimal"
          name: nixosiso
